# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lO0GSe2gmFs5OyZBjzjtE0GQlXL_YeDU
"""

import unittest
import requests

class TestVerifyLoginAPI(unittest.TestCase):

    def test_invalid_login_credentials(self):

        api_url = "https://automationexercise.com/api/verifyLogin"


        payload = {"email": "invalid_email@example.com", "password": "invalid_password"}


        response = requests.post(api_url, data=payload)


        self.assertEqual(response.status_code, 404, f"Beklenen 404 Not Found, ancak {response.status_code} alındı")


        beklenen_mesaj = "User not found!"
        self.assertEqual(response.text, beklenen_mesaj, f"Beklenen mesaj: '{beklenen_mesaj}', ancak '{response.text}' alındı")

if __name__ == '__main__':
    unittest.main()