# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10u82FGq85_--5ublIfmahCXMFgLZuipn
"""

pip install requests

import unittest
import requests

class TestProductAPI(unittest.TestCase):

    def test_post_istegi_desteklenmiyor(self):

        api_url = "https://automationexercise.com/api/productsList"


        response = requests.post(api_url)


        self.assertEqual(response.status_code, 405, f"Beklenen 405 Method Not Allowed, ancak {response.status_code} alındı")


        beklenen_mesaj = "Bu istek methodu desteklenmiyor."
        self.assertEqual(response.text, beklenen_mesaj, f"Beklenen mesaj: '{beklenen_mesaj}', ancak '{response.text}' alındı")

if __name__ == '__main__':
    unittest.main()