# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CJzQJTbELRthxxdvVizoud-fHlQ0Vs3v
"""

import unittest
import requests

class TestDeleteAccountAPI(unittest.TestCase):

    def test_delete_account(self):

        api_url = "https://automationexercise.com/api/deleteAccount"


        payload = {
            "email": "mirac@example.com",
            "password": "SecurePassword123"
        }


        response = requests.delete(api_url, data=payload)


        self.assertEqual(response.status_code, 200, f"Beklenen 200 OK, ancak {response.status_code} alındı")


        beklenen_mesaj = "Account deleted!"
        self.assertEqual(response.text, beklenen_mesaj, f"Beklenen mesaj: '{beklenen_mesaj}', ancak '{response.text}' alındı")

if __name__ == '__main__':
    unittest.main()