# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18NZ4rTWhE0sy7wtb6NgkgXTNps4a5Wir
"""

import unittest
import requests

class TestVerifyLoginAPI(unittest.TestCase):

    def test_delete_request_not_supported(self):

        api_url = "https://automationexercise.com/api/verifyLogin"


        response = requests.delete(api_url)


        self.assertEqual(response.status_code, 405, f"Beklenen 405 Method Not Allowed, ancak {response.status_code} alındı")


        beklenen_mesaj = "This request method is not supported."
        self.assertEqual(response.text, beklenen_mesaj, f"Beklenen mesaj: '{beklenen_mesaj}', ancak '{response.text}' alındı")

if __name__ == '__main__':
    unittest.main()