# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pCe20t3CtIbn9AgNgx-z6e6ptt2dJmOE
"""

import unittest
import requests

class TestVerifyLoginAPI(unittest.TestCase):

    def test_verify_login(self):

        api_url = "https://automationexercise.com/api/verifyLogin"


        payload = {"email": "test@example.com", "password": "password123"}


        response = requests.post(api_url, data=payload)


        self.assertEqual(response.status_code, 200, f"Beklenen 200 OK, ancak {response.status_code} alındı")


        beklenen_mesaj = "User exists!"
        self.assertEqual(response.text, beklenen_mesaj, f"Beklenen mesaj: '{beklenen_mesaj}', ancak '{response.text}' alındı")

if __name__ == '__main__':
    unittest.main()