# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11sskjjkKBLchzGnwEYVcKOosyN56SC1U
"""

import unittest
import requests

class TestUpdateAccountAPI(unittest.TestCase):

    def test_update_account(self):

        api_url = "https://automationexercise.com/api/updateAccount"


        payload = {
            "name": "Mirac Ozbalci",
            "email": "mirac@example.com",
            "password": "SecurePassword123",
            "title": "Mr",
            "birth_date": "01",
            "birth_month": "01",
            "birth_year": "1999",
            "firstname": "Mirac",
            "lastname": "Ozbalci",
            "company": "Updated ABC Company",
            "address1": "456 Street",
            "address2": "Apt 789",
            "country": "Turkiye",
            "zipcode": "54321",
            "region": "Marmara",
            "city": "Istanbul",
            "mobile_number": "+9876543210"
        }


        response = requests.put(api_url, data=payload)


        self.assertEqual(response.status_code, 200, f"Beklenen 200 OK, ancak {response.status_code} alındı")


        beklenen_mesaj = "User updated!"
        self.assertEqual(response.text, beklenen_mesaj, f"Beklenen mesaj: '{beklenen_mesaj}', ancak '{response.text}' alındı")

if __name__ == '__main__':
    unittest.main()