# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RKo36mO70TgXgdp5OmaALauFRHrGukAD
"""

import unittest
import requests

class TestSearchProductAPI(unittest.TestCase):

    def test_search_product(self):

        api_url = "https://automationexercise.com/api/searchProduct"


        payload = {"search_product": "tshirt"}


        response = requests.post(api_url, data=payload)


        self.assertEqual(response.status_code, 200, f"Beklenen 200 OK, ancak {response.status_code} alındı")


        self.assertEqual(response.headers["Content-Type"], "application/json", "Cevap JSON formatında değil")


        json_data = response.json()
        self.assertIn("searched_products", json_data, "JSON içinde 'searched_products' anahtarı bulunamadı")



if __name__ == '__main__':
    unittest.main()