# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gBun4qTqWuGat1v-07UAd8onVcVHjgwu
"""

pip install requests

import unittest
import requests

class TestProductAPI(unittest.TestCase):

    def test_get_products_list(self):

        api_url = "https://automationexercise.com/api/productsList"


        response = requests.get(api_url)


        self.assertEqual(response.status_code, 200, f"Expected 200 OK, but got {response.status_code}")


        self.assertEqual(response.headers["Content-Type"], "application/json", "Response is not in JSON format")


        json_data = response.json()
        self.assertIn("products", json_data, "Key 'products' not found in the JSON")



if __name__ == '__main__':
    unittest.main()