# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qG9YtNfrMV3Cqmn1v245eWC76VHOZLJ8
"""

import unittest
import requests

class TestVerifyLoginAPI(unittest.TestCase):

    def test_missing_email_or_password_param(self):

        api_url = "https://automationexercise.com/api/verifyLogin"


        response = requests.post(api_url)


        self.assertEqual(response.status_code, 400, f"Beklenen 400 Bad Request, ancak {response.status_code} alındı")


        beklenen_mesaj = "Bad request, email or password parameter is missing in POST request."
        self.assertEqual(response.text, beklenen_mesaj, f"Beklenen mesaj: '{beklenen_mesaj}', ancak '{response.text}' alındı")

if __name__ == '__main__':
    unittest.main()