# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1chWZ-vs76EVfgDjF5v9wj8ObPRax1Soc
"""

import unittest
import requests

class TestBrandsAPI(unittest.TestCase):

    def test_put_request_not_supported(self):

        api_url = "https://automationexercise.com/api/brandsList"


        response = requests.put(api_url)


        self.assertEqual(response.status_code, 405, f"Beklenen 405 Method Not Allowed, ancak {response.status_code} alındı")


        beklenen_mesaj = "This request method is not supported."
        self.assertEqual(response.text, beklenen_mesaj, f"Beklenen mesaj: '{beklenen_mesaj}', ancak '{response.text}' alındı")

if __name__ == '__main__':
    unittest.main()