# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1705dTHo9rP781f2O8Uso3_elzmX79yWb
"""

import unittest
import requests

class TestBrandsAPI(unittest.TestCase):

    def test_get_brands_list(self):

        api_url = "https://automationexercise.com/api/brandsList"


        response = requests.get(api_url)


        self.assertEqual(response.status_code, 200, f"Beklenen 200 OK, ancak {response.status_code} alındı")


        self.assertEqual(response.headers["Content-Type"], "application/json", "Cevap JSON formatında değil")


        json_data = response.json()
        self.assertIn("brands", json_data, "JSON içinde 'brands' anahtarı bulunamadı")



if __name__ == '__main__':
    unittest.main()