# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O0VUOO1cbEt-ufolg6DCm4jxK_cTt5nW
"""

import unittest
import requests

class TestCreateAccountAPI(unittest.TestCase):

    def test_create_account(self):

        api_url = "https://automationexercise.com/api/createAccount"


        payload = {
            "name": "Mirac Ozbalci",
            "email": "mirac@example.com",
            "password": "SecurePassword123",
            "title": "Mr",
            "birth_date": "01",
            "birth_month": "01",
            "birth_year": "1999",
            "firstname": "Mirac",
            "lastname": "Ozbalci",
            "company": "ABC Company",
            "address1": "123 Street",
            "address2": "Apt 456",
            "country": "Turkiye",
            "zipcode": "12345",
            "region": "Marmara",
            "city": "Istanbul",
            "mobile_number": "+1234567890"
        }


        response = requests.post(api_url, data=payload)


        self.assertEqual(response.status_code, 201, f"Beklenen 201 Created, ancak {response.status_code} alındı")


        beklenen_mesaj = "User created!"
        self.assertEqual(response.text, beklenen_mesaj, f"Beklenen mesaj: '{beklenen_mesaj}', ancak '{response.text}' alındı")

if __name__ == '__main__':
    unittest.main()